# General Settings
name: Kalys Osmonov
job_title: Full Stack Web Developer
email: kalys@osmonov.com
description: I build great products at Railsware, currently Calendly. I'm member of Planetary Society and space enthusiast.
avatar: /public/avatar.png
favicon: /favicon.ico
twitter_handler: kalysosmonov
analytics_code: UA-5801861-3
disqus: unyuuu

# Social Accounts
social_networks:
-  { name: github, url: 'https://github.com/kalys' }
-  { name: linkedin, url: 'https://www.linkedin.com/in/osmonov/' }
-  { name: twitter, url: 'https://twitter.com/kalysosmonov' }
-  { name: facebook, url: 'https://facebook.com/osmonov' }
-  { name: instagram, url: '' }
-  { name: google-plus, url: '' }
-  { name: skype, url: '' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }
-  { name: bitcoin, url: '' }
-  { name: pocket, url: '' }
-  { name: applemusic, url: '' }

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 1
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: ""
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed

